### ISSUE TITLE
AttributeError when I log in workflowy.

### ISSUE THREAD

**Issue by daehyok** [EcmaXp/wfapi#1]
As soon as I log in my workflowy account, I got the following error message. Could you fix it for me?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/dshin/mywork/projects/workflowy/tagdate.py in <module>()
      3 # login by password
      4 Workflowy(username="ehp.systemunit@gmail.com",
----> 5           password="*PASSWORD*")

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/workflowy.py in __init__(self, share_id, sessionid, username, password)
     60         if sessionid is not None or username is not None:
     61             username_or_sessionid = sessionid or username
---> 62             self.login(username_or_sessionid, password)
     63 
     64         self.init(share_id)

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/workflowy.py in login(self, username_or_sessionid, password, auto_init, use_ajax_login)
    172 
    173         if auto_init:
--> 174             return self.init(home_content=home_content)
    175 
    176     _SCRIPT_TAG_REGEX = re.compile("".join([

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/workflowy.py in init(self, *args, **kwargs)
     99         # TODO: give argument to smart handler? (_init require argument!)
    100         with self.smart_handle_init():
--> 101             self._init(*args, **kwargs)
    102 
    103     @property

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/workflowy.py in _init(self, share_id, home_content)
    232         self.nodemgr.update_root(
    233             root_project=self.main_project.pop("rootProject"),
--> 234             root_project_children=self.main_project.pop("rootProjectChildren"),
    235         )
    236         self.handle_init()

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/nodemgr.py in update_root(self, root_project, root_project_children)
     20 
     21     def update_root(self, root_project, root_project_children):
---> 22         self.root = self.new_root_node(root_project, root_project_children)
     23 
     24     def __setitem__(self, projectid, node):

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/nodemgr.py in new_root_node(self, root_project, root_project_children)
    136 
    137         root_project.update(ch=root_project_children)
--> 138         root = self.new_node_from_json(root_project)
    139         self.add(root, update_child=True)
    140         return root

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/nodemgr.py in new_node_from_json(self, data, parent)
     77 
     78     def new_node_from_json(self, data, parent=None):
---> 79         return self.NODE_CLASS.from_json(data, parent=parent)
     80 
     81     def add(self, node, update_child=True):

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_json(cls, data, parent)
    279             new_ch = []
    280             for child in ch:
--> 281                 child = cls.from_json(child)
    282                 new_ch.append(child)
    283             data["ch"] = new_ch

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_json(cls, data, parent)
    279             new_ch = []
    280             for child in ch:
--> 281                 child = cls.from_json(child)
    282                 new_ch.append(child)
    283             data["ch"] = new_ch

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_json(cls, data, parent)
    279             new_ch = []
    280             for child in ch:
--> 281                 child = cls.from_json(child)
    282                 new_ch.append(child)
    283             data["ch"] = new_ch

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_json(cls, data, parent)
    279             new_ch = []
    280             for child in ch:
--> 281                 child = cls.from_json(child)
    282                 new_ch.append(child)
    283             data["ch"] = new_ch

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_json(cls, data, parent)
    279             new_ch = []
    280             for child in ch:
--> 281                 child = cls.from_json(child)
    282                 new_ch.append(child)
    283             data["ch"] = new_ch

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_json(cls, data, parent)
    283             data["ch"] = new_ch
    284 
--> 285         info = WFRawNode.from_vaild_json(data)
    286         info.parent = parent
    287         return cls(info)

/Users/dshin/anaconda/lib/python3.5/site-packages/wfapi/node.py in from_vaild_json(cls, info)
     33         setattr_node = super(cls, self).__setattr__
     34         for k, v in value.items():
---> 35             setattr_node(k, v)
     36 
     37         return self

AttributeError: 'WFRawNode' object has no attribute 'lmb'

**Comment by EcmaXp** [comment]
@daehyok Don't post password =_=

I edit the comment and don't worry.
