### ISSUE TITLE
What is the integer number of node.completed_at?

### ISSUE THREAD

**Issue by daehyok** [EcmaXp/wfapi#3]
Trying to find date and time when a node is completed but can't find a document about what node.completed_at is storing. Could you tell me about it and how to convert it to date time.datetime()?

**Comment by EcmaXp** [comment]
Add date_joined_timestamp_in_seconds will get correct unix timestamp.

but i will fix that.

**Comment by daehyok** [comment]
Thanks for your fix. I love this feature.
now Node.last_modified and Node.completed_at return datetime object.
